apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  name: goapp-goapp-service-001
  namespace: test-playground
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: goapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-goapp-deployment-001
  namespace: test-playground
spec:
  replicas: 3
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
      - image: 981935913893.dkr.ecr.us-west-2.amazonaws.com/k8-go-server:dummy
        name: goapp
        ports:
        - containerPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/group.name: goapp-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  name: goapp-test-ingress-001
  namespace: test-playground
spec:
  ingressClassName: alb
  rules:
  - host: goapp.little-engine.com
    http:
      paths:
      - backend:
          service:
            name: goapp-goapp-service-001
            port:
              number: 80
        path: /
        pathType: Prefix
